/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 AppropriateUseOfTheDBMSWeb.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Service_2(props) {
  const { nodes, materials } = useGLTF('/3D objects/Service_2/AppropriateUseOfTheDBMSWeb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Database.geometry} material={materials.Database_Material}>
        <mesh geometry={nodes.Connections.geometry} material={materials.Database_Material} position={[2.59, 3.14, 0]} scale={1.27} />
      </mesh>
      <mesh geometry={nodes.Database_Data_1.geometry} material={materials.Database_Material} position={[2.44, 3.97, 0]} scale={[1.18, 1, 0.1]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Data_Material_1} position={[0.29, 0.54, 0.59]} scale={[0.53, 0.16, 0.91]} />
      </mesh>
      <mesh geometry={nodes.Database_Data_2.geometry} material={materials.Database_Material} position={[-2.42, 3.98, 0]} scale={[1.18, 1, 0.1]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.Data_Material_1} position={[0.78, -0.46, 0.59]} scale={[0.07, 0.24, 0.91]} />
      </mesh>
      <mesh geometry={nodes.Database_Data_3.geometry} material={materials.Database_Material} position={[-3.79, 0.7, 0]} scale={[1.18, 1, 0.1]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials.Data_Material_2} position={[-0.03, -0.71, 0.59]} scale={[0.62, 0.16, 0.91]} />
      </mesh>
      <mesh geometry={nodes.Database_Data_4.geometry} material={materials.Database_Material} position={[3.85, 0.7, 0]} scale={[1.18, 1, 0.1]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Data_Material_2} position={[-0.03, -0.71, 0.59]} scale={[0.62, 0.16, 0.91]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3D objects/Service_2/AppropriateUseOfTheDBMSWeb-transformed.glb')
