/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 DatabaseWeb.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Service_3(props) {
  const { nodes, materials } = useGLTF('./3D objects/Service_3/DatabaseWeb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, -0.08, 0.27]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-1.23, -10.55, -8.35]}>
          <group position={[0, -16.16, -37.88]}>
            <mesh geometry={nodes['1'].geometry} material={materials['default']} position={[31.99, 2.24, 2.88]} rotation={[0, 1.57, 0]} />
            <mesh geometry={nodes['2'].geometry} material={materials['default']} position={[0, 52.94, -0.01]} />
            <mesh geometry={nodes['3'].geometry} material={materials.Gabetas_Material} />
          </group>
          <group position={[0, 20, -1.14]}>
            <mesh geometry={nodes['5'].geometry} material={materials['default']} position={[31.99, 2.24, 2.88]} rotation={[0, 1.57, 0]} />
            <mesh geometry={nodes['10'].geometry} material={materials['default']} position={[0, 52.98, 0.14]} />
          </group>
          <group position={[0, 34.04, 36.14]}>
            <mesh geometry={nodes['9'].geometry} material={materials['default']} position={[31.99, 2.24, 2.88]} rotation={[0, 1.57, 0]} />
            <mesh geometry={nodes['3_2'].geometry} material={materials['default']} position={[0, 52.98, 0]} />
            <mesh geometry={nodes['12'].geometry} material={materials.Gabetas_Material} />
          </group>
        </group>
        <group position={[2.45, 37.06, 17.64]}>
          <group position={[10.71, -1.97, -22.29]} rotation={[-0.21, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Кольцо.geometry} material={materials['default']} position={[14.13, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки.geometry} material={materials['default']} position={[26.88, 4, -23.27]} />
            <mesh geometry={nodes.Основа1.geometry} material={materials.Book_Material_1} position={[20.57, -0.03, -14.45]} />
            <mesh geometry={nodes.Основа2.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3.geometry} material={materials['Book_Material_1.1']} />
            <mesh geometry={nodes.ПолуКруг.geometry} material={materials['default']} position={[14.29, -0.03, -24.45]} />
          </group>
          <group position={[10.71, 7.75, -21.48]} rotation={[-0.22, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Кольцо_2.geometry} material={materials['default']} position={[14.13, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_2.geometry} material={materials['default']} position={[26.88, 4, -23.27]} />
            <mesh geometry={nodes.Основа1_2.geometry} material={materials.Book_Material_2} position={[20.57, -0.03, -14.45]} />
            <mesh geometry={nodes.Основа2_2.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3_2.geometry} material={materials['default']} />
            <mesh geometry={nodes.ПолуКруг_2.geometry} material={materials['default']} position={[14.29, -0.03, -24.45]} />
          </group>
          <group position={[10.71, 14.7, -21.57]} rotation={[-0.14, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Кольцо_3.geometry} material={materials['default']} position={[14.13, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_3.geometry} material={materials['default']} position={[26.88, 4, -23.27]} />
            <mesh geometry={nodes.Основа2_3.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3_3.geometry} material={materials['Book_Material_1.1']} />
            <mesh geometry={nodes.ПолуКруг_3.geometry} material={materials['default']} position={[14.29, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа1_3.geometry} material={materials.Book_Material_1} />
          </group>
          <group position={[-4.74, -18, 13.59]} rotation={[-1.11, 0, 0]}>
            <mesh geometry={nodes.Кольцо_4.geometry} material={materials['default']} position={[-5.37, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_4.geometry} material={materials['default']} position={[7.38, 4, -23.27]} />
            <mesh geometry={nodes.Основа1_4.geometry} material={materials['default']} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.ПолуКруг_4.geometry} material={materials['default']} position={[-5.21, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа2_4.geometry} material={materials.Gabetas_Material} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.Основа3_4.geometry} material={materials['default']} position={[1.07, -0.03, -14.45]} />
          </group>
          <group position={[-4.74, -5.71, 14.41]} rotation={[-0.92, 0, 0]}>
            <mesh geometry={nodes.Кольцо_5.geometry} material={materials['default']} position={[-5.37, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_5.geometry} material={materials['default']} position={[7.38, 4, -23.27]} />
            <mesh geometry={nodes.ПолуКруг_5.geometry} material={materials['default']} position={[-5.21, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа3_5.geometry} material={materials['default']} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.Основа1_5.geometry} material={materials.Book_Material_2} />
            <mesh geometry={nodes.Основа2_5.geometry} material={materials['default']} />
          </group>
          <group position={[-4.74, 2.37, 14.82]} rotation={[-0.57, 0, 0]}>
            <mesh geometry={nodes.Кольцо_6.geometry} material={materials['default']} position={[-5.37, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_6.geometry} material={materials['default']} position={[7.38, 4, -23.27]} />
            <mesh geometry={nodes.Основа1_6.geometry} material={materials.Database_Middle_Material} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.ПолуКруг_6.geometry} material={materials['default']} position={[-5.21, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа2_6.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3_6.geometry} material={materials['default']} />
          </group>
          <group position={[-4.74, 9.3, 15.57]} rotation={[-0.28, 0, 0]}>
            <mesh geometry={nodes.Кольцо_7.geometry} material={materials['default']} position={[-5.37, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_7.geometry} material={materials['default']} position={[7.38, 4, -23.27]} />
            <mesh geometry={nodes.Основа1_7.geometry} material={materials.Gabetas_Material} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.ПолуКруг_7.geometry} material={materials['default']} position={[-5.21, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа2_7.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3_7.geometry} material={materials['default']} />
          </group>
          <group position={[-4.74, 16.22, 16.39]} rotation={[-0.09, 0, 0]}>
            <mesh geometry={nodes.Кольцо_8.geometry} material={materials['default']} position={[-5.37, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_8.geometry} material={materials['default']} position={[7.38, 4, -23.27]} />
            <mesh geometry={nodes.Основа1_8.geometry} material={materials.Database_Material} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.ПолуКруг_8.geometry} material={materials['default']} position={[-5.21, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа2_8.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3_8.geometry} material={materials['default']} />
          </group>
          <group position={[-4.74, 22.95, 16.55]}>
            <mesh geometry={nodes.Кольцо_9.geometry} material={materials['default']} position={[-5.37, -0.03, -28.92]} />
            <mesh geometry={nodes.Крепежки_9.geometry} material={materials['default']} position={[7.38, 4, -23.27]} />
            <mesh geometry={nodes.Основа1_9.geometry} material={materials.Database_Middle_Material} position={[1.07, -0.03, -14.45]} />
            <mesh geometry={nodes.ПолуКруг_9.geometry} material={materials['default']} position={[-5.21, -0.03, -24.45]} />
            <mesh geometry={nodes.Основа2_9.geometry} material={materials['default']} />
            <mesh geometry={nodes.Основа3_9.geometry} material={materials['default']} />
          </group>
        </group>
        <group position={[-1.23, -26.51, -9.29]}>
          <mesh geometry={nodes['1_2'].geometry} material={materials.Database_Material} />
          <mesh geometry={nodes.C_2.geometry} material={materials.Database_Middle_Material} position={[0, 0, 4.75]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./3D objects/Service_3/DatabaseWeb-transformed.glb')
