/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Service_1.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Service_1(props) {
  const { nodes, materials } = useGLTF('./3D objects/Service_1/Service_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Coin_Material} />
      <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Database_Material} />
      <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.Gabinets_Materials} />
    </group>
  )
}

useGLTF.preload('./3D objects/Service_1/Service_1-transformed.glb')
